# Generated by Django 4.1.5 on 2023-02-24 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("project_cd", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25, verbose_name="プロジェクト名")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="開始日"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="終了日"),
                ),
                (
                    "details",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="詳細"
                    ),
                ),
                ("update_date", models.DateField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leader",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="プロジェクトリーダー",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectToUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="task.project"
                    ),
                ),
                (
                    "user_cd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
