# Generated by Django 4.1.5 on 2023-03-08 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_projectmember"),
    ]

    operations = []
